services:
  - type: web
    name: brotel-ms
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: DATA_DIR
        value: /var/data
      - key: MONGODB_URI
        sync: false
    disk:
      name: brotel-ms-data
      mountPath: /var/data
      sizeGB: 1
